### ISSUE TITLE
Erro ao instalar

### ISSUE THREAD

**Issue by caduvieira** [rafpyprog/amanuense#2]
Comando: pip install amanuense

Collecting amanuense
  Downloading amanuense-0.0.1a0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-l5w9a4/amanuense/setup.py", line 5, in <module>
        from amanuense.__init__ import __version__
      File "amanuense/__init__.py", line 1, in <module>
        from .diario import *
      File "amanuense/diario.py", line 71
    SyntaxError: Non-ASCII character '\xc3' in file amanuense/diario.py on line 71, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-l5w9a4/amanuense/
****

**Comment by licensed** [comment]
> Comando: pip install amanuense
> 
> Collecting amanuense
> Downloading amanuense-0.0.1a0.tar.gz
> Complete output from command python setup.py egg_info:
> Traceback (most recent call last):
> File "", line 1, in
> File "/tmp/pip-build-l5w9a4/amanuense/setup.py", line 5, in
> from amanuense.**init** import **version**
> File "amanuense/**init**.py", line 1, in
> from .diario import *
> File "amanuense/diario.py", line 71
> SyntaxError: Non-ASCII character '\xc3' in file amanuense/diario.py on line 71, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
> 
> ```
> ----------------------------------------
> ```
> 
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-l5w9a4/amanuense/

Você tá usando python 2? Aqui não apresentou problemas na instalação (Python 3.8.1)

**Comment by FelipeAmaral13** [comment]
pip install amanuense
Defaulting to user installation because normal site-packages is not writeable
Collecting amanuense
  Using cached amanuense-0.0.1a0.tar.gz (3.9 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\felipesa\\Local Settings\\Temp\\pip-install-t4u7cwaf\\amanuense\\setup.py'"'"'; __file__='"'"'C:\\Users\\felipesa\\Local Settings\\Temp\\pip-install-t4u7cwaf\\amanuense\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\felipesa\Local Settings\Temp\pip-pip-egg-info-46z99ucc'
         cwd: C:\Users\felipesa\Local Settings\Temp\pip-install-t4u7cwaf\amanuense\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\felipesa\Local Settings\Temp\pip-install-t4u7cwaf\amanuense\setup.py", line 23, in <module>
        long_description=read('README.rst'),
      File "C:\Users\felipesa\Local Settings\Temp\pip-install-t4u7cwaf\amanuense\setup.py", line 9, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "c:\program files\python38\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 132: character maps to <undefined>
    ` ----------------------------------------`
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

    ` ----------------------------------------`
Utilizando o Python 3 3.8.3
